### ISSUE TITLE
USER STORY: GitHub Environment Set Up 

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#1]
As a **Developer** I can **set up a project environment in GitHub** so that **I can manage version control and project planning**

**Acceptance Criteria:**

      1. New GitHub repository with appropriate name for PP4
      2. Able to use repository to create workspace in GitPod
      3. Working Add, Commit and Push functionality

**Tasks:**

- [x] Create new PP4 repository - TasteSENsation
- [x] Create project within the repository
- [x] Create new User Story Template
- [x] Create labels for MoSCoW prioritisation
- [x] Create labels for Story Points
- [x] Create Milestones for each Sprint with due date attached
