### ISSUE TITLE
USER STORY: View a list of recipes

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#11]
As a **User** I can **view a list of all recipes** so that **I can choose which one to try for myself**

**Acceptance Criteria:**

      1. User can see all recipes in descending order of date created (most recent first) 
      2. 
      3.

**Tasks:**

- [x] In the 'cookbook' directory create new urls.py
- [x] Open tastesensation/urls.py
- [x] Ensure include is imported from django.urls (after path)
- [x] Add url pattern: path("", include("cookbook.urls"), name="cookbook-urls"),
- [x] Create 'templates' folder in cookbook app and create another folder within the templates folder called 'cookbook'
- [x] Create html file called recipe_list.html
- [x] In cookbook/views.py file import generic from django.views and from .models import Recipe model
- [x] Create class based view called RecipeList(generic.ListView)
- [x] In empty cookbook/urls.py add [from . import views] and [from django.urls import path]
- [x] Add urlpattern for RecipeList: path("", views.RecipeList.as_view(), name="home"),
- [x] Check if recipes displayed in browser
