### ISSUE TITLE
USER STORY: Submit a Recipe Rating

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#12]
As a **registered user** I can **submit a recipe review** so that **others can see whether this is a good recipe**

**Acceptance Criteria:**

      1. User can see the average rating from other people's ratings
      2. User can rate the recipe for themselves (1-5 stars)
      3. User can edit or delete the review

**Tasks:**

- [x] Create Rating model
- [x] Add url path to cookbook/urls.py: path('rate/<int:post_id>/<int:rating>/', views.rate),
- [x] Update views.py to check if user has made any ratings to display
- [x] Update html to display average star rating within recipe card
- [x] Add styling to css
- [x] Test if average rating displayed
- [x] Test if user rating is displayed
- [x] Test if user can edit / update their rating
