### ISSUE TITLE
USER STORY:  Submit a Feedback Comment

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#14]
As a **User** I can **submit a feedback comment for a recipe** so that **others can see my opinion on that recipe**

**Acceptance Criteria:**

      1. A registered user can select from a drop down menu to leave an example comment or write one of their own
      2. A registered user has the option to update or delete their comment
      3. 

**Tasks:**

- [x] Add choices to the comment model for example comments to choose from
- [x] Install crispy forms and bootstrap for crispy 
- [x] Define fields to use in comment form (comment_selection and own_comment)
- [x] Test to check all viewing correctly
- [x] Use print statements to check that POST is working correctly in print_detail view.
