### ISSUE TITLE
USER STORY: Sort recipes by ratings

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#15]
As a **user** I can **choose to order the recipes list according to their rating** so that **I can see the top rated recipes first**

**Acceptance Criteria:**

      1. User can click a button to sort the recipes by star ratings or by date created
      2. Recipes are displayed with highest ratings first and lowest ratings last
      3. Order reverts back to order by date created when page is refreshed.

**Tasks:**

- [ ] Update view to get a recipe list which includes the average rating for each recipe
- [ ] Add sort by method to the recipe list view to sort by highest ranking to lowest ranking
- [ ] Add button to template to trigger sorted(recipe_list, average_rating) function to run in view
