### ISSUE TITLE
USER STORY: Log In

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#17]
As a **registered user** I can **log in to the application** so that **I can see my profile and leave reviews on recipes**

**Acceptance Criteria:**

      1. Registered User and Administrator can log in via a link in the navigation bar
      2. User is shown appropriate content for their access rights
      3. If not registered user or administrator, user is given error message and redirected to registration page.

**Tasks:**

- [x] Create login link in navigation bar
- [x] Create a test user
- [x] Create a test staff administrator
- [x] Test that login for each test user works
- [x] Test that registered user does not have access to create new recipe
- [x] Test that error message and redirection work with incorrect credentials

**Epic:**
#8
