### ISSUE TITLE
USER STORY: Deploy to Heroku

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#18]
As a **Developer** I can **deploy my project to Heroku** so that **there is a cloud-based version of my project for testing and assessment**

**Acceptance Criteria:**

      1. Working deployed application hosted in Heroku
      2. DEBUG setting is set to False
      3. All sensitive data is included in env.py file to keep it secure

**Tasks:**

- [x] Create Heroku App
- [x] Link Heroku app to GitHub Repo
- [x] Update code ready for deployment (e.g. requirements.txt)
- [x] Ensure you have a Procfile
- [x] Ensure the database url is included in the env.py and that env.py is included in the .gitignore file
- [x] Commit and Push to GitHub
- [x] Update Config Vars in Heroku
- [x] Deploy branch manually in Heroku and open to check it works
