### ISSUE TITLE
USER STORY: Write User Stories

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#2]
As a **Developer** I can **write user stories** so that **I can make sure that all project objectives are met**

**Acceptance Criteria:**

      1. A range of user stories from the SEN User perspective
      2. A range of user stories from the Admin perspective
      3. A range of user stories from the Developer perspective

**Tasks:**

- [x] Brainstorm and write user stories
- [x] Assign MoSCoW Label
- [x] Assign Milestone
- [x] Add to 'To Do' list
- [x] Assign Story Points
