### ISSUE TITLE
USER STORY: Implement User Registration

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#20]
As a **User** I can **register on the site** so that **I can add my own feedback and track my favourite recipes**

**Acceptance Criteria:**

      1. Unregistered users can submit registration form to register on the site
      2. Fields are populated with helpful guidance to aid SEN Users
      3.  Once registered the user can log in immediately

**Tasks:**

- [x] Create register / sign-up link in navigation bar
- [x] Install AllAuth to manage user registration
- [x] Test registration submission is creating a new user
- [x] Add css styling to html templates
