### ISSUE TITLE
USER STORY: Select recipes 'Want to Try'

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#21]
As a **User** I can **select recipes that I would like to try later** so that **I can quickly find recipes that I might want to cook when I return to the site**

**Acceptance Criteria:**

      1. Option to select 'Want to Try' button on each recipe card
      2. 'Want to Try' recipes are tagged with a colour-coded tag to be easily identifiable
      3. 'Want to Try' recipes are priorities in the recipe list on the landing page
      4. User can easily remove all tags and leave untagged or reassign to 'Cooked!' or 'Don't Like'

**Tasks:**

- [ ] Add a 'Want to Try' button to the html for recipe cards
- [ ] Create colour coded tag to act as visual identifier
- [ ] Update code to check if any recipes have been tagged as 'Want to Try' and add these to user's profile list
- [ ] Create option for removing all tags
- [ ] Test to check that tag is added / removed as expected
