### ISSUE TITLE
USER STORY: Tag recipes as 'Don't Like'

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#22]
As a **User** I can **select recipes that I do not like the sound of** so that **these are moved to the bottom of the recipe list when I return to the site**

**Acceptance Criteria:**

      1. Option to select 'Don't Like' button on each recipe card
      2. 'Don't Like' recipes are tagged with a colour-coded tag to be easily identifiable
      3. 'Don't Like' recipes are moved to the bottom of the recipe list on the landing page
      4. User can easily remove all tags and leave blank or reassign to 'Completed' or 'Want to Try'

**Tasks:**

- [ ] Add a 'Don't Like' button to the html for recipe cards
- [ ] Create colour coded tag to act as visual identifier
- [ ] Update code to check if any recipes have been tagged as 'Don't Like' and overwrite default order_by function to display these last
- [ ] Create option for removing all tags
- [ ] Test to check that tag is added / removed as expected
