### ISSUE TITLE
USER STORY: Highlight cooked recipes to track progress

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#23]
As a User I can identify recipes that I have tried out so that I can keep track of my progress and go back to recipes that I enjoy.

**Acceptance Criteria:**

      1. Option for registered users to mark recipe as 'Cooked!' on each recipe card
      2. Labelled recipes are clearly identifiable with colour coded thicker border and tick icon
      3. When recipe labelled as 'cooked' user sees a modal to congratulate them and ask if they would like to leave a review

**Tasks:**

- [ ] Add a 'Cooked!' button to the html for recipe cards
- [ ] Add styling to css for recipe card to be added if cooked=True
- [ ] Create modal to congratulate user and redirect to comment function for that recipe.
- [ ] Check if cooked=True and add to user profile recipe list
- [ ] Test to check that styling is applied as expected when cooked=True
- [ ] Test that recipe is added to 'cooked_list' as expected.
