### ISSUE TITLE
USER STORY: Implement Data Validation in Database Models

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#24]
As a **Developer** I can **implement data validation rules** so that **all fields in the database models are configured correctly using the most appropriate field type**

**Acceptance Criteria:**

      1. All data types for each field are the most suitable type for the data to be entered
      2. All field specs identified in each ERD are properly coded and working
      3. If incorrect data entered, user receives an error message and is prompted to try again

**Tasks:**

- [x] Set correct data type for all fields
- [x] Set all required fields to ```required=True```
- [x] Set all required fields that can be nullable to ```null=True```
- [x] Set all required fields that must be unique (e.g. recipe ID) ```unique=True```
- [x] Create Superuser
- [x] Test each data type by inserting correct and incorrect data
- [x] Create error message modal for incorrect data entry
