### ISSUE TITLE
USER STORY: Tag recipe as a 'Favourite'

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#25]
As a **User** I can **tag a recipe as one of my favourites** so that **I can quickly find recipes that I would like to make again or share with others**

**Acceptance Criteria:**

      1. User can click on heart icon in the recipe card to identify as a 'favourite'
      2. Heart icon is displayed as full and red when identified as a favourite
      3. User can deselect heart icon to remove 'favourite' label
      4. Favourite recipes are listed on the profile page

**Tasks:**

- [ ] Add a heart icon as an event listener in the top corner of the recipe card
- [ ] If heart icon clicked, change styling to full red heart
- [ ] Update code so if ```favourite=True``` then recipe is added to 'favourite' list and displayed in User Profile
- [ ] Test if styling is updated when heart is clicked
- [ ] Test if recipe is added to favourite list when heart is clicked
