### ISSUE TITLE
USER STORY: Update CSS Styling for SEN Users

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#26]
As a **Developer** I can **set styling in a css file** so that **the look and feel of the site is consistent across all pages, is fully responsive and is tailored to the needs of users with Special Educational Needs**

**Acceptance Criteria:**

      1. All pages of the site are consistent using a base file for the header and footer elements.
      2. Instructions are clear, concise and easy to follow
      3. Visual cues, colour coding, and icons are used to enhance understanding for SEN users 
      4. Layouts are well spaced out with minimal distractions and unnecessary JavaScript code
      5. Font size is easily readable and passes all accessibility validation with excellent contrast

**Tasks:**

- [x] Review each page of the site and ensure that all header and footer styling is displaying as expected
- [x] Add icons and colour styling to buttons to ensure they stand out and have clear instruction
- [x] Review spacing on all page layouts and increase white space or reduce content where necessary to minimise distraction
- [x] Include clear instructions / call to action buttons for going back to main recipes page
