### ISSUE TITLE
USER STORY: WAVE and WCAG compatibility

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#27]
As a **Site Developer** I can **ensure that all pages are configured correctly for page readers ** so that **SEN users and all abilities are able to navigate the site easily**

**Acceptance Criteria:**

      1. All visual content has consistent and descriptive aria tags and alternative text wherever appropriate
      2. When passed through WAVE accessibility evaluation tool (https://wave.webaim.org/), all pages pass with high ratings
      3. All WAVE accessibility evaluation results are included in project README.md file

**Tasks:**

- [x] Run recipe list (landing page) through WAVE Tool
- [x] Run registration page through WAVE Tool
- [x] Run recipe details page through WAVE Tool
- [x] Run any other pages not listed above through WAVE Tool
