### ISSUE TITLE
USER STORY: W3C validation (HTML)

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#29]
As a **Site Developer** I can **ensure that all HTML code is correct** so that **my site is accessible and performs well**

**Acceptance Criteria:**

      1. All HTML pages pass through W3C validation with no major errors (https://validator.w3.org/)
      2.
      3.

**Tasks:**

- [x] Run recipe list (landing page) through W3C Validation Tool
- [x] Run registration page through W3C Validation Tool
- [x] Run profile page through W3C Validation Tool
- [x] Run recipe details page through W3C Validation Tool
- [x] Run any other pages not listed above through W3C Validation Tool
