### ISSUE TITLE
USER STORY: Display appliances and skills information

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#32]
As a **Site Developer** I can **add icons to each recipe card to indicate which appliances and skills are required** so that **users can judge whether this recipe is the right level for them to attempt**

**Acceptance Criteria:**

      1. Simple icons on the recipe card indicate what appliances and skills are required for the recipe
      2. Icons are supported by descriptive aria tags so users using a page reader receive helpful information
      3. Aria tags also serve as subtitles to provide helpful information explaining the icons

**Tasks:**

- [x] Identify appropriate icons for: Boiling, Frying, Baking, Chopping, Mixing, Straining, Mashing, Blending, Whisking
- [x] Update code to check if each appliance / skill is required and display the appropriate icon with subtitle on the recipe card
- [x] Test that the correct icons display as expected when added to recipe details
