### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#33]
As a **Registered User or Staff Administrator** I can **log out of the site** so that **if my device is left unattended others cannot access areas that are not meant for them**

**Acceptance Criteria:**

      1. When logged in, Registered Users and Staff Administrators can log out by clicking on a 'Log Out' button
      2. 
      3. 

**Tasks:**

- [x] Create log out button
- [x] Add event listener to trigger login to be reset to False when button clicked
- [x] Create alert message popup to confirm that the user has successfully logged out
- [x] Test if possible to add a review once logged out
