### ISSUE TITLE
USER STORY: Display difficulty rating for recipe

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#34]
As a **Staff Administrator** I can **add a difficulty level for each recipe** so that **registered users can easily find recipes at an appropriate skill level for them**

**Acceptance Criteria:**

      1. Difficulty level is displayed in the recipe details
      2. Difficult level is easy to read and understand
      3. 

**Tasks:**

- [ ] Define difficulty rating options and descriptions indicating low, medium and high skill requirements
- [ ] Identify an appropriate visual representation (bar chart / gauge graphic) to display
- [ ] Add difficulty field to recipe model
- [ ] Update code to translate selected difficulty level (1, 2, 3, 4, 5) into graphic representation
- [ ] Test that appropriate graphic is displayed according to difficulty level
