### ISSUE TITLE
USER STORY: Define database models

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#36]
As a **Developer** I can **create an ERD for each database model** so that **I have a blueprint to use when creating the model**

**Acceptance Criteria:**

      1. Completer ERD for each model
      2. Each ERD includes all fields, field types, authentication and key info
      3. 

**Tasks:**

- [x] List all required data models (relating to each page of the site)
- [x] Create an ERD for each model
- [x] Add ERDs to README files
