### ISSUE TITLE
USER STORY: View a Recipe

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#38]
As a **User** I can **view a full recipe** so that **I can see what ingredients are required, follow the steps to cook the recipe and leave a review for that recipe if I wish**

**Acceptance Criteria:**

      1. The user can click on a button within the recipe card to see a recipe detail page
      2. The recipe detail page includes a link to read other's reviews and leave a review of your own
      3. Each recipe detail page shows a hero image and the skills, ingredients and instructions required to complete that recipe

**Tasks:**

- [x] Build layout for recipe image, skills, ingredients and instructions
- [x] Add average rating and form to add your own rating
- [x] Add functionality to view comments
- [x] Add comment form to post comments to the recipe
- [x] Update template to hide rating and comment forms and ask user to log in if not already logged in as a user
