### ISSUE TITLE
USER STORY: Set Up Django Project 

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#4]
As a **Developer** I can **create and connect a new Django project** so that **I have a base template to start working in**

**Acceptance Criteria:**

      1. A new Django Project with all associated files pushed to GitHub Repo
      2. Project works on a browser
      3. 

**Tasks:**

- [x] Install packages 
- [x] Create Django project & app
- [x] Add app to Setting.py
- [x] Create Views & URLs
- [x] Test finished app works in browser
