### ISSUE TITLE
USER STORY: Update (edit) or Delete a comment on a recipe

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#43]
As a **Site User** I can **edit or remove my comment** so that **I can change what I have written if I change my mind or make a mistake.**

**Acceptance Criteria:**

      1. When logged in, a user can see all their pending and approved comments
      2. When logged in, a user can select a comment to edit or delete by clicking on a button
      3. The comment can be edited or deleted and the updated comment is shown, or it is removed

**Tasks:**

- [x] Add a comment_edit function based view to get the comment and display content within the commentForm
- [x] Add url path to urls.py
- [x] Add an Edit Comment button to the template
- [x] Add JavaScript to get comment content and run comment_edit view
- [x] Open and update a comment 
- [x] Check that the comment has been updated correctly
