### ISSUE TITLE
USER STORY: Delete Recipe as Recipe Owner

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#47]
As a **Site User** I can **log in and delete recipes that I have submitted as the recipe 'owner'** so that **I can choose not to share recipe if I change my mind.**

**Acceptance Criteria:**

      1. When logged in, the user can click on a button to edit any recipe that they submitted as the recipe 'owner'
      2. The logged in recipe owner can also click on a button to delete a recipe with a modal prompt to confirm
      3.

**Tasks:**

- [x] Add recipe_delete view to views
- [x] Add a recipe_delete url path
- [x] Add a Delete Recipe button to be visible to the recipe 'owner' only
- [x] Write JavaScript to add event listener to Delete Recipe button, retrieve the correct recipe and show the delete confirmation modal
- [x] Check that only recipe 'owner' can see the delete button and use authentication to ensure they are logged in.
- [x] Check that the modal shows and that confirmation in the modal results in recipe deletion.
