### ISSUE TITLE
USER STORY: Create PostgreSQL database

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#5]
As a **Developer** I can **use a PostgreSQL database** so that **I can manipulate data in my Django project**

**Acceptance Criteria:**

      1. A working PostgreSQL database with create CRUD functionality
      2. PostgreSQL Database is connected to Heroku
      3.

**Tasks:**

- [x] Create PostgreSQL instance
- [x] Connect database to code
- [x] Enter data into the database
- [x] Deploy the project
- [x] Connect Heroku to the PostgreSQL database
