### ISSUE TITLE
USER STORY: Filter Recipe List by star rating

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#52]
As a **site user** I can **select a filter option** so that **I can see a subset of recipes that have good feedback from other people.**

**Acceptance Criteria:**

      1. User can select each of the star ratings to filter recipes with that current rating level.
      2. User can also choose to revert to see all recipes with all star ratings
      3.

**Tasks:**

- [x] Create a form with dropdown options in the index template to enable user to select which rating they want to filter by
- [x] Update the RecipeList view to identify a rating_filter
- [x] Use the rating_filter to create a filtered_recipes list for the specified filter
- [x] Add an option for 'All Recipes' which shows recipes with all ratings
- [x] Add an 'Unrated' option to show recipes with no ratings yet
- [x] Check that only recipes with the correct ratings are shown
- [x] Check that filters work across pagination
