### ISSUE TITLE
USER STORY: Map out model schema

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/TasteSENsation#6]
As a **Developer** I can **create a model schema** so that **I have a blueprint for a database that defines how data is organised and connected**

**Acceptance Criteria:**

      1. A schema diagram containing an ERD for each model
      2. Relationships between primary and foreign keys are shown
      3. 

**Tasks:**

- [x] Identify how each Django view will request data from each model to display in a UI template
- [x] Identify any Primary / Foreign Keys
- [x] Add ERD for each model and to schema diagram
- [x] Add visual representation of relationships between models
- [x] Add schema diagram to README files
